acronyms = {
    "SNOTEL_SWE_M_0": 'SWE M1',
    "SNOTEL_SWE_A_0": 'SWE A1',
    "SNOTEL_PA_M_0": 'PA M1',
    "SNOTEL_PA_A_0": 'PA A1',
    "SNOTEL_SWE_M_1": 'SWE M2',
    "SNOTEL_SWE_A_1": 'SWE A2',
    "SNOTEL_PA_M_1": 'PA M2',
    "SNOTEL_PA_A_1": 'PA A2',
    "SNOTEL_SWE_M_2": 'SWE M3',
    "SNOTEL_SWE_A_2": 'SWE A3',
    "SNOTEL_PA_M_2": 'PA M3',
    "SNOTEL_PA_A_2": 'PA A3',
    "SNOTEL_SWE_M_3": 'SWE M4',
    "SNOTEL_SWE_A_3": 'SWE A4',
    "SNOTEL_PA_M_3": 'PA M4',
    "SNOTEL_PA_A_3": 'PA A4',
    "SNOTEL_SWE_M_4": 'SWE M5',
    "SNOTEL_SWE_A_4": 'SWE A5',
    "SNOTEL_PA_M_4": 'PA M5',
    "SNOTEL_PA_A_4": 'PA A5',
    "SNOTEL_SWE_M_5": 'SWE M6',
    "SNOTEL_SWE_A_5": 'SWE A6',
    "SNOTEL_PA_M_5": 'PA M6',
    "SNOTEL_PA_A_5": 'PA A6',
    "SNOTEL_SWE_M_6": 'SWE M7',
    "SNOTEL_SWE_A_6": 'SWE A7',
    "SNOTEL_PA_M_6": 'PA M7',
    "SNOTEL_PA_A_6": 'PA A7',
    "SNOTEL_SWE_M_7": 'SWE M8',
    "SNOTEL_SWE_A_7": 'SWE A8',
    "SNOTEL_PA_M_7": 'PA M8',
    "SNOTEL_PA_A_7": 'PA A8',
    "SNOTEL_SWE_M_8": 'SWE M9',
    "SNOTEL_SWE_A_8": 'SWE A9',
    "SNOTEL_PA_M_8": 'PA M9',
    "SNOTEL_PA_A_8": 'PA A9',
    "SPFH_mean": 'SPFH',
    "TMP_mean": 'TMP',
    "WIND_mean": 'WIND',
    "SOI": 'SOI',
    "PDO": 'PDO',
    "NAO": 'NAO',
    "AMO": 'AMO'
}


colors = {
    "SNOTEL_SWE_M_0": '#E97B30',
    "SNOTEL_SWE_A_0": '#E97B30',
    "SNOTEL_PA_M_0": '#F8C7A6',
    "SNOTEL_PA_A_0": '#F8C7A6',
    "SNOTEL_SWE_M_1": '#E97B30',
    "SNOTEL_SWE_A_1": '#E97B30',
    "SNOTEL_PA_M_1": '#F8C7A6',
    "SNOTEL_PA_A_1": '#F8C7A6',
    "SNOTEL_SWE_M_2": '#E97B30',
    "SNOTEL_SWE_A_2": '#E97B30',
    "SNOTEL_PA_M_2": '#F8C7A6',
    "SNOTEL_PA_A_2": '#F8C7A6',
    "SNOTEL_SWE_M_3": '#E97B30',
    "SNOTEL_SWE_A_3": '#E97B30',
    "SNOTEL_PA_M_3": '#F8C7A6',
    "SNOTEL_PA_A_3": '#F8C7A6',
    "SNOTEL_SWE_M_4": '#E97B30',
    "SNOTEL_SWE_A_4": '#E97B30',
    "SNOTEL_PA_M_4": '#F8C7A6',
    "SNOTEL_PA_A_4": '#F8C7A6',
    "SNOTEL_SWE_M_5": '#E97B30',
    "SNOTEL_SWE_A_5": '#E97B30',
    "SNOTEL_PA_M_5": '#F8C7A6',
    "SNOTEL_PA_A_5": '#F8C7A6',
    "SNOTEL_SWE_M_6": '#E97B30',
    "SNOTEL_SWE_A_6": '#E97B30',
    "SNOTEL_PA_M_6": '#F8C7A6',
    "SNOTEL_PA_A_6": '#F8C7A6',
    "SNOTEL_SWE_M_7": '#E97B30',
    "SNOTEL_SWE_A_7": '#E97B30',
    "SNOTEL_PA_M_7": '#F8C7A6',
    "SNOTEL_PA_A_7": '#F8C7A6',
    "SNOTEL_SWE_M_8": '#E97B30',
    "SNOTEL_SWE_A_8": '#E97B30',
    "SNOTEL_PA_M_8": '#F8C7A6',
    "SNOTEL_PA_A_8": '#F8C7A6',
    "SPFH_mean": '#94AEDC',
    "TMP_mean": '#94AEDC',
    "WIND_mean": '#94AEDC',
    "SOI": '#C6E0B4',
    "PDO": '#C6E0B4',
    "NAO": '#C6E0B4',
    "AMO": '#C6E0B4'
}
